import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton} from '@clerk/nextjs'
import { dark } from "@clerk/themes";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-900 `}>
          <header className="flex justify-between bg-zinc-600 items-center h-13 px-3 sm:px-5 md:px-10 lg:px-20 xl:px-30 sticky top-0 z-50">
            <Link href={'/dashboard'}>
            <Image src={'/askmypdf.png'} alt="PDF" width={140} height={140} />
            </Link>
            <SignedOut>
              <div>
                <SignInButton>
                  <Button className="bg-gray-300 text-black hover:bg-gray-50 mr-2">
                    Sign In
                  </Button>
                </SignInButton>
                <SignUpButton>
                  <Button className="hover:bg-gray-700">
                    Sign Up
                  </Button>
                </SignUpButton>
              </div>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <div className="sm:px-5 md:px-10 lg:px-30 xl:px-40">
            <Toaster position="top-center" richColors/>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
